name: Publish Release

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]

    name: Publish for Java ${{ matrix.java }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          # The name of the environment variable, not its value
          gpg-passphrase: OSSRH_GPG_SECRET_KEY_PASSWORD

      - name: List GPG Keys
        run: gpg --list-secret-keys --keyid-format LONG

      - name: Store tag name as version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to Maven Central
        run: ./gradlew publish -Pversion=${{ env.RELEASE_VERSION }} -Psigning.gnupg.keyName=${{ secrets.OSSRH_GPG_SECRET_KEY_ID }} -Psigning.gnupg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
